
revision: "1-24-3"

service:
  type: None

labels:
  app: ingressgateway
  istio: ingressgateway

autoscaling:
  minReplicas: 2
  maxReplicas: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 128Mi