app:
  replicas: 1
  image: beer1/saga-example-product-service:dev
  port: 6020
  resources:
    requests: 
      cpu: "0.1"
      memory: 512Mi
    limits:
      memory: 512Mi
  env:
    - name: JAVA_TOOL_OPTIONS
      value: |
        -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError
        -XX:InitialRAMPercentage=50 -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=50
        -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=64m
        -XX:+UseParallelGC
    - name: SPRING_JPA_GENERATE_DDL
      value: "true"
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://mysql-headless.middleware.svc.cluster.local:3306/saga_product?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom: 
        secretKeyRef:
          name: mysql-credentials
          key: username
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: mysql-credentials
          key: password
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: kafka.middleware.svc.cluster.local:9092
podLabels:
  tier: backend
  prometheus.io/monitor-target: "spring-app"

probes:
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: 6020
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness: 
    httpGet:
      path: /actuator/health/liveness
      port: 6020
    initialDelaySeconds: 120
    periodSeconds: 10

service:
  enabled: true
