apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oom-test-besteffort
  name: oom-test-besteffort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-test-besteffort
  template:
    metadata:
      labels:
        app: oom-test-besteffort
    spec:
      containers:
      - image: beer1/oom-test
        imagePullPolicy: Always
        name: oom-test
        resources: {}