apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      path: istio/routing-rules
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy: {}