server:
  retention: "15d"
  global:
    scrape_interval: 5s
    scrape_timeout: 2s
    evaluation_interval: 1m

  persistentVolume:
    enabled: true
    storageClass: hostpath
    size: 30Gi
  
  resources: 
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi    

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
  hostRootFsMount:
    enabled: false

alertmanager:
  enabled: false
  
prometheus-pushgateway:
  enabled: false
