apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: cicd
spec:
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: 9.4.5
      helm:
        releaseName: grafana
        valueFiles:
          - $values/monitoring/grafana.yaml
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      ref: values
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true