apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: cicd
spec:
  sources:
    - repoURL: 'oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack'
      targetRevision: 77.6.2
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/monitoring/kube-prometheus-stack.yaml
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      ref: values
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true