apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitors
  namespace: cicd
spec:
  sources:
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      path: monitoring/prometheus-monitors
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy: 
    automated:
      selfHeal: true