apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: cicd
spec:
  sources:
    - repoURL: 'oci://ghcr.io/argoproj/argo-helm/argo-rollouts'
      path: .
      targetRevision: 2.40.5
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/cicd/argo-rollouts.yaml
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      ref: values
  destination:
    name: ''
    namespace: cicd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true