apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-app
  namespace: monitoring
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http
  selector:
    matchLabels:
      prometheus.io/monitor-target: "spring-app"
