apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-app
  namespace: monitoring
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
  - path: /actuator/prometheus
    port: http
    interval: 15s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      prometheus.io/monitor-target: "spring-app"
